#!/usr/bin/env python3
"""Play the three confirmed scenery boundaries in the actual offline renderer.

Optional --snapshots reuses natural Race.tick snapshots saved by an audit.
Without it, the same states are regenerated by the production engine. Videos
and frame samples permit human review; assertions do not certify aesthetics.
"""
import argparse
import asyncio
import hashlib
import json
from pathlib import Path
from playwright.async_api import async_playwright

ROOT = Path(__file__).resolve().parents[2]


async def main(args):
    args.out.mkdir(parents=True, exist_ok=True)
    report = {'checks': [], 'errors': [], 'externalRequests': [], 'quality': 'full',
              'protocol': 'Natural stage 5/19 seed 2058765; actual 1x RAF, 1440x1000 DPR1; no injected rider positions.'}
    async with async_playwright() as pw:
        browser = await pw.chromium.launch(headless=True)
        report['browser'] = browser.version
        for version in ['V24', 'V25']:
            src = ROOT / ('Grand-Tour-' + version + '.html')
            for name, stage, time in [('village', 4, 9.5), ('tree-line', 18, 127), ('finish-crowd', 4, 268.1)]:
                folder = args.out / (version + '-' + name)
                folder.mkdir(exist_ok=True)
                context = await browser.new_context(viewport={'width': 1440, 'height': 1000}, device_scale_factor=1,
                                                    record_video_dir=str(folder), record_video_size={'width': 1440, 'height': 1000})
                await context.set_offline(True)
                page = await context.new_page()
                page.on('pageerror', lambda e: report['errors'].append(str(e)))
                page.on('request', lambda r: report['externalRequests'].append(r.url) if r.url.startswith(('http:', 'https:')) else None)
                await page.goto(src.as_uri() + '?test')
                await page.evaluate("App.testingFreeze=true;App.blockStoreWrite=true;Store.settings.quality='full'")
                await page.evaluate('document.fonts.ready')
                if args.snapshots:
                    snap = json.loads((args.snapshots / ('natural-' + name + '-before.json')).read_text(encoding='utf-8'))
                    # Production persistence accepts Tour active states only.
                    # As in retained scene_verify, promote only this envelope;
                    # all physical, timing and RNG fields stay byte-for-byte.
                    await page.evaluate("s=>initializeRace(Race.restore({...s,mode:'tour'}))", snap)
                else:
                    await page.evaluate('''({stage,time})=>{const r=new Race(stage,0,'single',null,2058765);
                        for(let i=0;i<Math.round(time/CONFIG.step);i++)r.tick();initializeRace(r);}''', {'stage': stage, 'time': time})
                start = await page.evaluate('''()=>{const r=App.race;r.paused=false;App.testingFreeze=true;
                    viewFor(r).alpha=1;drawRace();updateHud(true);return {t:r.t,x:r.player.x,alt:r.player.alt};}''')
                await page.screenshot(path=str(folder / 'frame-0.png'))
                await page.evaluate('App.testingFreeze=false')
                samples = []
                for i in range(1, 7):
                    await page.wait_for_timeout(400)
                    samples.append(await page.evaluate('({t:App.race.t,x:App.race.player.x,alt:App.race.player.alt,low:RenderBudget.low()})'))
                    await page.screenshot(path=str(folder / f'frame-{i}.png'))
                result = await page.evaluate('''()=>{App.testingFreeze=true;const r=App.race,v=viewFor(r),before=JSON.stringify(r.snapshot());
                    for(let i=0;i<12;i++)drawRace();
                    const error=Math.max(0,...v.drawn.map(o=>Math.abs(o.x-(v.projection.anchor+(o.v.world-v.projection.playerX)*v.projection.scaleX))));
                    return {t:r.t,pure:before===JSON.stringify(r.snapshot()),projectionError:error,low:RenderBudget.low()};}''')
                passed = result['t'] > start['t'] + 1 and result['pure'] and result['projectionError'] < 1e-8 and not result['low']
                report['checks'].append({'version': version, 'scene': name, 'sourceSHA256': hashlib.sha256(src.read_bytes()).hexdigest(),
                                         'start': start, 'samples': samples, **result, 'pass': passed})
                await context.close()
                print(version, name, json.dumps(result), flush=True)
        await browser.close()
    report['passed'] = sum(c['pass'] for c in report['checks'])
    report['failed'] = len(report['checks']) - report['passed']
    report['skipped'] = 0
    report['pass'] = not report['failed'] and not report['errors'] and not report['externalRequests']
    (args.out / 'continuity-browser.json').write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding='utf-8')
    assert report['pass'], report


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--snapshots', type=Path)
    parser.add_argument('--out', type=Path, required=True)
    asyncio.run(main(parser.parse_args()))
